name: Get latest book list from Goodreads
on:
  schedule:
    # Run once a week on Thursdays
    - cron: "0 0 * * 4"
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update currently reading list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "152411532"
          shelf: "currently-reading"
